version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: take2-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: take2
      MARIADB_USER: root
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - take2-net

volumes:
  mariadb_data:

networks:
  take2-net:
    driver: bridge
