teams = {
    'HG': 'Homestead Grays',
    'HIL': 'Hilldale Club',
    'IA': 'Indianapolis Athletics',
    'IAB': 'Atlanta Black Crackers',
    'IC': 'Indianapolis Clowns',
    'ID': 'Indianapolis ABCs II',
    'JRC': 'Jacksonville Red Caps',
    'KCM': 'Kansas City Monarchs',
    'LRG': 'Little Rock Grays',
    'LVB': 'Louisville Black Caps',
    'MB': 'Milwaukee Bears',
    'MGS': 'Montgomery Grey Sox',
    'MRM': 'Monroe Monarchs',
    'MRS': 'Memphis Red Sox',
    'NBY': 'New York Black Yankees',
    'ND': 'Newark Dodgers',
    'NE': 'Newark Eagles',
    'NLG': 'New York Lincoln Giants',
    'NS': 'Newark Stars',
    'NWB': 'Newark Browns',
    'NYC': 'New York Cubans',
    'PBG': 'Philadelphia Bacharach Giants',
    'PK': 'Pittsburgh Keystones II',
    'PS': 'Philadelphia Stars',
    'PTG': 'Philadelphia Tigers',
    'SEN': 'Washington Black Senators',
    'SL2': 'St. Louis Stars II',
    'SLS': 'St. Louis Stars I',
    'TC': 'Pittsburgh Crawfords',
    'TT': 'Toledo Tigers',
    'WAP': 'Washington Pilots',
    'WMP': 'Washington Potomacs',
    'ABC': 'Indianapolis ABCs',
    'AC': 'Bacharach Giants Team',
    'AG': 'Akron Grays',
    'BBB': 'Birmingham Black Barons',
    'BBS': 'Baltimore Black Sox',
    'BEG': 'Baltimore Elite Giants',
    'BGI': 'Brooklyn Royal Giants',
    'CAG': 'Chicago American Giants',
    'CBB': 'Columbus Blue Birds',
    'CBE': 'Cleveland Buckeyes',
    'CBN': 'Cleveland Browns',
    'CCU': 'Cleveland Cubs',
    'CEL': 'Cleveland Elites',
    'CG': 'Cleveland Giants',
    'CHT': 'Cleveland Hornets',
    'CST': 'Cleveland Stars',
    'COB': 'Columbus Buckeyes',
    'COG': 'Chicago Giants',
    'COT': 'Columbus Turfs',
    'CRS': 'Cleveland Red Sox',
    'CSE': 'Cuban Stars East I',
    'CSW': 'Cuban Stars West',
    'CT': 'Cincinnati Tigers',
    'CTG': 'Cleveland Tigers',
    'CTS': 'Cleveland Tate Stars',
    'CUP': 'Pollocks Cuban Stars',
    'DYM': 'Dayton Marcos',
    'DS': 'Detroit Stars',
    'DTS': 'Detroit Stars II',
    'DW': 'Detroit Wolves',
    'SOH': 'St. Louis-New Orleans-Harrisburg Stars',
    'HBG': 'Harrisburg Giants'
}